app = "federated-learning-server" # Make sure this is unique
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

# HTTP service for the Flask API
[[services]]
  protocol = "tcp"
  internal_port = 5000 # Gunicorn runs on this port
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

# Raw TCP service for Flower clients
[[services]]
  protocol = "tcp"
  internal_port = 8080 # Flower server runs on this port
  processes = ["app"]

  [[services.ports]]
    port = 8080